### ISSUE TITLE
add bind-plugins package

### ISSUE THREAD

**Issue by jongj** [ventz/docker-bind#21]
Please also add the bind-plugins package to the container. 

This package contains the filter-aaaa plugin. Starting from 9.14 this filter was split-off from the main package

Some more info on how to use the plugin: ftp://ftp.isc.org/isc/bind9/cur/9.14/doc/arm/man.filter-aaaa.html

**Comment by ventz** [comment]
@jongj Thanks! - added and pushed out as 7cd4708

At the next update, will add to the point release. For now, it's part of ":latest"
