### ISSUE TITLE
Posibility to change exec named variables

### ISSUE THREAD

**Issue by emitosolini** [ventz/docker-bind#27]
Hi, is it possible to remove the "-g" in the execution command of named? Because I would like to output the logs to files instead of the console.

File: docker-bind/container/entrypoint.sh
Run in foreground and log to STDERR (console):
exec /usr/sbin/named -c /etc/bind/named.conf **-g** -u named $OPTIONS

Thanks in advance.
Best.

**Comment by ventz** [comment]
@emitosolini You can simply override the --entrypoint argument with a custom one (or a custom command).

That said - generally, you want to output to stdout+stderr, and redirect that (via the docker engine natively) to a log.

see: https://docs.docker.com/config/containers/logging/configure/

**Comment by emitosolini** [comment]
Hi @ventz, could you give me an example of the ussage of --entrypoint? I'm kind of new to Docker and this variables some times gets tricky.

I see the point about the logs, but I already have the logging preferences in named.conf, and if is possible would like to keep it that way.

Thanks.

**Comment by ventz** [comment]
See: https://docs.docker.com/engine/reference/run/

You can pass your own start command or even custom file.
