### ISSUE TITLE
how do I pass logging options to container?

### ISSUE THREAD

**Issue by ffabreti** [ventz/docker-bind#32]
By default, I see almost no logging.
I'd like to log queries refused, not found, and errors in general.

my docker run:
```
docker run \
 --name=bind9 \
 --volume="/srv/bind9/etc/bind:/etc/bind" \
 --volume="/srv/bind9/var/cache/bind:/var/cache/bind" \
 -p 53:53 -p 53:53/udp \
 --restart=unless-stopped \
 --detach=true \
 ventz/bind:9.14.7-r0

**Comment by ventz** [comment]
@ffabreti The logs are console by default (docker logs -f $container)

If you want more details - ex, query logging, you can add something like this to the named.conf:
```
logging {
    channel query_log {
        //file "/var/log/bind/query.log" versions 3 size 5m;
        file "named.log" versions 3 size 5m;
        severity dynamic;
        print-category yes;
        print-severity yes;
        print-time yes;
    };
    category queries { query_log; };
};
```

**Comment by ffabreti** [comment]
I have done something similar, but got this on reload:

`04-Feb-2020 19:26:40.684 not using config file logging statement for logging due to -g option
`
my config is:
```
logging {
    channel my_log {
        stderr;
        severity info;
        print-category no;
        print-severity no;
        print-time yes;
    };
   category security { my_log; };
   category dnssec   { my_log; };
   category default  { my_log; };
};

**Comment by ventz** [comment]
Can you remove the stderr and try again.

See: https://www.zytrax.com/books/dns/ch7/logging.html
(Specifically, bit about mutual exclusive - I believe you can't try to pipe to syslogd)
> 

syslog syslog_facility | 'syslog' indicates that this channel will use syslogd logging features (as defined in syslog.conf). The syslog_facility is the facility definition for 'syslog' and may be found in syslog's man pages. From the grammar above 'file', 'syslog', 'stderr' and 'null' are mutually exclusive for a 'channel'.
-- | --

**Comment by ffabreti** [comment]
Hi Ventz,
I have remove stderr and added syslog (cannot simply remove stderr)
```
logging {

    channel my_log {
        //stderr;
        syslog 0;
        severity info;
        print-category no;
        print-severity no;
        print-time yes;
    };
   category security { my_log; };
   category dnssec   { my_log; };
   category default  { my_log; };
};
```
The message remains the same:
`not using config file logging statement for logging due to -g option`

**Comment by ffabreti** [comment]
I have  also done exactly what you suggested on first comment.
got same message on reload.
named.log is empty.

**Comment by ventz** [comment]
Give me a little bit time - I'll try to get you a working config. It's also very possible also that something has changed on the latest version of bind/alpine (alpine I know went to the 10x branch, and we upgraded bind a few versions recently.)

**Comment by ventz** [comment]
@ffabreti Ok, here's a working config:

1.) add to your `named.conf`:
```
...
include "/etc/bind/named.conf.logging";
...
```

2.) create a file `named.conf.logging`:
```
logging {

    channel stdout {
        stderr;
        severity info;
        print-category no;
        print-severity no;
        print-time yes;
    };
   category security { stdout; };
   category dnssec   { stdout; };
   category default  { stdout; };
};
```

I can start it with:
```
docker run -d \
--name bind \
-v /docker/etc/bind:/etc/bind \
-v /docker/bind/var/cache/bind:/var/cache/bind \
-p 53:53 -p 53:53/udp \
ventz/bind
```

and after doing just a test dig (`dig a test.com @localhost`), see the log:
```
06-Feb-2020 21:02:01.902 client @0x561cf1a52bc0 172.17.0.1#48746 (test.com): query (cache) 'test.com/A/IN' denied
```

Hopefully this works for you - and if it does, I'll update the README.

**Comment by ffabreti** [comment]
Thanks. I'll test it on monday and post here.

**Comment by ffabreti** [comment]
Hi there, 

Same message (`not using config file logging statement for logging due to -g option`) 
I am running  ventz/bind:9.14.7-r0

**Comment by ffabreti** [comment]
I've upgrade to latest image (ventz/bind:9.14.8-r0) and results are the same.

I mean, I don't see any logs, like you when running `dig`

My host is CentOS7
My Docker version is 19.03.5

**Comment by ventz** [comment]
@ffabreti Just to confirm, the container is starting with the above logging config and running, but you can't see the logs? (if so - that's a different problem).

Just to confirm - the logs are in the `docker logs -f $container` (vs any file) and you are seeing nothing there? This may be a docker engine configuration issue, or even just having a LOG plugin enabled - which is the recommended way to log to files from docker.

Depending no how you are binding/which interface on your host, the dig may have to be at the IP address of your CentOS7 host vs localhost/127.0.0.1

**Comment by ffabreti** [comment]
Yes, container starts normally, with logging config ,but I cannot see any logs (that should be logged by the new logging config) when I run `docker logs -f <container-name>`

This is the output:
```
11-Feb-2020 14:05:17.044 received control channel command 'reload'
11-Feb-2020 14:05:17.044 loading configuration from '/etc/bind/named.conf'
11-Feb-2020 14:05:17.046 reading built-in trust anchors from file '/etc/bind/bind.keys'
11-Feb-2020 14:05:17.092 using default UDP/IPv4 port range: [32768, 60999]
11-Feb-2020 14:05:17.092 using default UDP/IPv6 port range: [32768, 60999]
11-Feb-2020 14:05:17.093 no IPv6 interfaces found
11-Feb-2020 14:05:17.095 sizing zone task pool based on 24 zones
11-Feb-2020 14:05:17.097 none:100: 'max-cache-size 90%' - setting to 3410MB (out of 3789MB)
11-Feb-2020 14:05:17.099 obtaining root key for view _default from '/etc/bind/bind.keys'
11-Feb-2020 14:05:17.099 none:100: 'max-cache-size 90%' - setting to 3410MB (out of 3789MB)

11-Feb-2020 14:05:17.101 not using config file logging statement for logging due to -g option

11-Feb-2020 14:05:17.104 reloading configuration succeeded
11-Feb-2020 14:05:17.105 reloading zones succeeded
11-Feb-2020 14:05:17.109 zone ***************/IN: loaded serial 2020021101
11-Feb-2020 14:05:17.109 all zones loaded
11-Feb-2020 14:05:17.109 running
11-Feb-2020 14:05:17.109 zone ***************/IN: sending notifies (serial 2020021101)
11-Feb-2020 14:05:17.167 managed-keys-zone: Key 20326 for zone . is now trusted (acceptance timer complete)
11-Feb-2020 14:05:17.192 client @0x5581ae2e4500 ***************#46155 (***************): transfer of '***************/IN': AXFR-style IXFR started (serial 2020021101)
11-Feb-2020 14:05:17.192 client @0x5581ae2e4500 189.9.32.11#46155 (***************): transfer of '***************/IN': AXFR-style IXFR ended: 1 messages, 57 records, 1622 bytes, 0.001 secs (1622000 bytes/sec)
```

I'm binding to 0.0.0.0 (all):
`tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      20344/docker-proxy`

I don't remember changing any Docker log parameter or plugins. But if you point me out, I can double-check.
Thanks.

**Comment by ffabreti** [comment]
`docker inspect ******* | grep -i log -A5 -B5`
```
        "Image": "sha256:d728edd9105a13b898b810c3f31d5178a91f241a4ef5af73fd065b00ba2c40ad",
        "ResolvConfPath": "/var/lib/docker/containers/85fc184f6447a9f0ac198e4c4ba39c4a4d9e72b122ac1d1dc5732ba7db672df9/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/85fc184f6447a9f0ac198e4c4ba39c4a4d9e72b122ac1d1dc5732ba7db672df9/hostname",
        "HostsPath": "/var/lib/docker/containers/85fc184f6447a9f0ac198e4c4ba39c4a4d9e72b122ac1d1dc5732ba7db672df9/hosts",
        "LogPath": "/var/lib/docker/containers/85fc184f6447a9f0ac198e4c4ba39c4a4d9e72b122ac1d1dc5732ba7db672df9/85fc184f6447a9f0ac198e4c4ba39c4a4d9e72b122ac1d1dc5732ba7db672df9-json.log",
        "Name": "/bind9-externo",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
--
            "Binds": [
                "/**************:/etc/bind",
                "/***************:/var/cache/bind"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
```

**Comment by ventz** [comment]
@ffabreti Assuming you want to comment out your IP in the 2nd log (last line):
> 11-Feb-2020 14:05:17.192 client @0x5581ae2e4500...

By the way, you did the zone transfer request right from your system (per log)?

Can you try launching the container with this sample config -- attaching the volume mount "root" here:
[bind.zip](https://github.com/ventz/docker-bind/files/4187933/bind.zip)

And start with:

```
# note: $bind is the attachment root above

docker run -it --rm \
-v /docker/$bind/etc/bind:/etc/bind \
-v /docker/$bind/var/cache/bind:/var/cache/bind \
-p 53:53 -p 53:53/udp \
ventz/bind
```

I want to eliminate the container/user config vs docker engine config.

**Comment by magnusbaeck** [comment]
I can reproduce this as well, and from what I gather this is expected behavior with `-g` since it causes BIND to ignore the logging configuration in the configuration files and only log to stderr. Here's named(8):

```
       -f
           Run the server in the foreground (i.e. do not daemonize).

       -g
           Run the server in the foreground and force all logging to stderr.
```

The `-g` flag sets named_g_logstderr (https://github.com/isc-projects/bind9/blob/v9_16_0/bin/named/main.c#L764-L767) which causes the configuration loading logic to just validate the logging configuration and log the "not using config file logging statement for logging due to -g option" message without configuring anything: https://github.com/isc-projects/bind9/blob/v9_16_0/bin/named/server.c#L8803-L8824

Can't we use the `-f` flag instead? That'll still foreground BIND but won't force the logging to stderr. I don't know what the default logging behavior is in that case, but if it isn't stderr we should be able to supply a default configuration that maintains the current stderr behavior.

**Comment by ventz** [comment]
@magnusbaeck I used to use `-f` -- I believe there was some reason for going to `-g` (it was one of the open issues by someone I believe). I seem to remember that any error (actual stderr) msgs did not get logged. I think also to follow the docker standard for log drivers output, technically stdout and stderr both need to be forwarded, so that if someone swaps out the json-file with syslog or fluentd/etc, it will log everything.

**Comment by ventz** [comment]
Searched through the issues here and the ones people emailed -- I can't find anything. Maybe it's time to try out "-f"?

Thoughts?

I can do some testing to make sure the log pluggins do not break

**Comment by magnusbaeck** [comment]
Keeping `-g` as the default is probably a good idea since a change would be backwards incompatible, but we could make the behavior configurable via an environment variable, say, STDERR_LOGS_ONLY:

```bash
if [ "${STDERR_LOGS_ONLY:-true}" = "true" ] ; then
    exec /usr/sbin/named -c /etc/bind/named.conf -g -u named $OPTIONS
else
    exec /usr/sbin/named -c /etc/bind/named.conf -f -u named $OPTIONS
fi
```

**Comment by ffabreti** [comment]
Any updates on this ?

**Comment by ventz** [comment]
@ffabreti Yes - sorry for the delay, will make some changes and push today.

**Comment by ventz** [comment]
@ffabreti  @magnusbaeck All set - see: a4c9ab2
I think this is a nice/clean solution. Updated README too.

Also updated alpine image for binary docker image and tagged latest as `9.14.8-r5`

**Comment by ffabreti** [comment]
Hey @ventz,

Worked like a charm ! Thanks.

I did this:
```
logging {

    channel stdout {
        stderr;
        severity debug;
        print-category no;
        print-severity no;
        print-time yes;
    };
   category security { stdout; };
   category dnssec   { stdout; };
   category default  { stdout; };
   category queries  { stdout; };
};
```
Docker keeps receiving logs from the stderr, but now I can control `severity`.

example of output:
```
11-Mar-2020 14:00:09.357 client @0x561531a43cc0 187.66.54.228#53365 (aaaaaaa.mydomain.com): query: aaaaaaa.mydomain.com IN AAAA + (172.17.0.2)
11-Mar-2020 14:00:10.247 client @0x561531a528e0 177.149.152.207#26030 (ns1.mydomain.com): query: ns1.mydomain.com IN A -E(0)DC (172.17.0.2)
11-Mar-2020 14:00:15.190 client @0x561531a43cc0 146.112.139.67#63143 (processo.mydomain.com): query: processo.mydomain.com IN A -E(0)DC (172.17.0.2)
11-Mar-2020 14:00:15.573 client @0x561531a528e0 181.215.46.74#19873 (sso.mydomain.com): query: sso.mydomain.com IN AAAA -E(0)DC (172.17.0.2)
11-Mar-2020 14:00:32.849 client @0x561531a528e0 187.66.54.228#49521 (abc.com): query: abc.com IN A + (172.17.0.2)
11-Mar-2020 14:00:32.849 client @0x561531a528e0 187.66.54.228#49521 (abc.com): query failed (REFUSED) for abc.com/IN/A at query.c:5382
11-Mar-2020 14:00:32.899 client @0x561531a43cc0 187.66.54.228#49522 (abc.com): query: abc.com IN AAAA + (172.17.0.2)
11-Mar-2020 14:00:32.899 client @0x561531a43cc0 187.66.54.228#49522 (abc.com): query failed (REFUSED) for abc.com/IN/AAAA at query.c:5382
11-Mar-2020 14:00:38.382 client @0x561531a43cc0 131.255.39.222#24634 (ns1.mydomain.com): query: ns1.mydomain.com IN AAAA -E(0)DC (172.17.0.2)
```

**Comment by ventz** [comment]
Great!
