### ISSUE TITLE
please use COMMAND to lauch bind inside container, not ENTRYPOINT

### ISSUE THREAD

**Issue by rpodgorny** [ventz/docker-bind#33]
in other words, you should move the last line from entrypoint.sh to COMMAND dockerfile directive.

this will allow to launch bind with custom options but also launch other tools from the container.

**Comment by rpodgorny** [comment]
sorry, i meant CMD of course!

https://docs.docker.com/engine/reference/builder/#cmd

**Comment by rpodgorny** [comment]
...and https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#entrypoint

**Comment by ventz** [comment]
@rpodgorny There was a bug a while back which prevented sub-sub parameters from being passed correctly from docker to alpine's ash shell. I don't remember if it was docker or alpine related, but this was the reason for this solution. It currently allows for a "default" entrypoint for the image, and yet it still allows the user to override/add any bind parameters they wish -- no different than having CMD.

Technically, it limits the container's default behavior to bind, which is fine, but if you want to run another command (let's say `rndc-confgen` for example), you would have to override the `--entrypoint`

I am assuming you mean to have:

```
# cat Dockerfile
...
COPY entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
# Run in foreground and log to STDERR (console):
CMD ["exec", "/usr/sbin/named", "-c", "/etc/bind/named.conf", "-g", "-u", "named"]
```

```
# cat entrypoint.sh
#!/bin/sh
chown -R root:named /etc/bind /var/run/named
chown -R named:named /var/cache/bind
chmod -R 770 /var/cache/bind /var/run/named
chmod -R 750 /etc/bind
```

If this was fixed and it doesn't cause problems any longer, I have no problem with updating it.

**Comment by ventz** [comment]
Closing old issue - no updates / feedback
