### ISSUE TITLE
Tag Release

### ISSUE THREAD

**Issue by bclermont** [ventz/docker-bind#5]
instead of `latest` you should also keep a tag like `:9.9.3_p4` for every release of your image

**Comment by ventz** [comment]
@bclermont I can do that - I actually just submitted two bug requests (one of which is a critical remote vulnerability) for the Alpine -- so as soon as they patch, I'll tag the next release.

This originally started as a personal project, and I never assumed in my wildest dreams that > 10K people would use it :)

**Comment by ventz** [comment]
@bclermont Have not forgotten about the tagging. In fact, I just pushed out a major new release with a lot of changes in terms of default configs/examples/etc. I am going to tag it for the current version, and start tagging from now on.

The release is this one btw: https://github.com/ventz/docker-bind/commit/108554317ee821cc926109de9179fed4a1aed2ea

**Comment by bclermont** [comment]
ok please add the tag!

**Comment by ventz** [comment]
Will do - I want to add back the older dir (i've been going back and forth on it, and I think it makes sense to at least support all "standard and semi-standard" directories, and let the users choose).

Expect it in the next day or two -- and I'll release tag that one. I'll add a "RELEASE" file too that has some information on the tagged releases so people can always refer to them and know which change is present in each.

In the future -- after a new version/upgrades/upstream changes, a few days later when it's been "real world tested", i'll tag and release with that dates.

**Comment by ventz** [comment]
@bclermont All set: https://github.com/ventz/docker-bind/tree/9.11.2_p1-r0
(also, dockerhub tag: 9.11.2_p1-r0)

**Comment by bclermont** [comment]
Finally!

**Comment by bclermont** [comment]
Thanks @ventz

**Comment by ventz** [comment]
@bclermont No problem - sorry that it took this long. I have finally caught up with all of the requests, and can now focus on improving configs/examples. I'll still make sure that security updates are given top priority and are released within hours to a day of becoming publicly available.
